### ISSUE TITLE
Edit New issue OpenCV crash with some PNG Files

### ISSUE THREAD

**Issue by xkobal** [thumbor/opencv-engine#13]
Hello, 

We are using Thumbor for some resizing on Overblog (https://www.over-blog.com/) and it works very well, but we encounter problems with some PNG files.

We are using OpenCV engine because of its speed and smart detection, and we fallback on PIL when OpenCV crash.

Here is the version we use:
Pillow==2.3.2
opencv-engine==1.0.0
pgmagick==0.5.8
thumbor==4.8.2
thumbor-pexif==0.14.1
tornado==3.2.2

Works on Debian 7 with bundled OpenCV 2.4.10.

Here is an example of a PNG: http://img.over-blog-kiwi.com/0/88/72/24/20150107/ob_f75a17_jescharlie.png 

We resize with this command:
/unsafe/568x568/http://img.over-blog-kiwi.com/0/88/72/24/20150107/ob_f75a17_jescharlie.png
(I know it's an upscale)

It's the same with downscale: /unsafe/100x50/http://img.over-blog-kiwi.com/0/88/72/24/20150107/ob_f75a17_jescharlie.png

```
thumbor_opencv OpenCV Error: Assertion failed (src.depth() == dst.depth() && src.size == dst.size) in cvCopy, file /tmp/opencv-2.4.10/modules/core/src/copy.cpp, line 556
thumbor_opencv 2015-01-14 09:57:34 thumbor:ERROR ERROR: Traceback (most recent call last):
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1320, in _stack_context_handle_exception
thumbor_opencv     raise_exc_info((type, value, traceback))
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 302, in wrapped
thumbor_opencv     ret = fn(*args, **kwargs)
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/loaders/http_loader.py", line 54, in return_contents
thumbor_opencv     callback(response.body)
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 373, in handle_loader_loaded
thumbor_opencv     callback(normalized, engine=self.context.request.engine)
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 110, in callback
thumbor_opencv     self.filters_runner.apply_filters(thumbor.filters.PHASE_AFTER_LOAD, transform)
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/filters/__init__.py", line 81, in apply_filters
thumbor_opencv     callback()
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 108, in transform
thumbor_opencv     Transformer(self.context).transform(after_transform_cb)
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 88, in transform
thumbor_opencv     self.smart_detect()
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 123, in smart_detect
thumbor_opencv     self.do_image_operations()
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 195, in do_image_operations
thumbor_opencv     self.auto_crop()
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 247, in auto_crop
thumbor_opencv     self.engine.crop(crop_left, crop_top, crop_right, crop_bottom)
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/opencv_engine/engine.py", line 95, in crop
thumbor_opencv     cv.Copy(src_region, cropped)
thumbor_opencv error: src.depth() == dst.depth() && src.size == dst.size
```

Works very well with PIL.

Thanks for your work and your help.

**Comment by sskylar** [comment]
Noticed this problem on a few PNGs:

```
OpenCV Error: Assertion failed (src.type() == dst.type()) in cvResize, file /tmp/opencv-pcqRHK/opencv-2.4.10.1/modules/imgproc/src/imgwarp.cpp, line 4074
2015-02-22 15:02:42 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1320, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1503, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/imaging.py", line 100, in get
    self.check_image(kw)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/imaging.py", line 96, in check_image
    return self.execute_image_operations()
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 89, in execute_image_operations
    self.filters_runner.apply_filters(thumbor.filters.PHASE_PRE_LOAD, self.get_image)
  File "/usr/local/lib/python2.7/site-packages/thumbor/filters/__init__.py", line 81, in apply_filters
    callback()
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 114, in get_image
    self._fetch(self.context.request.image_url, self.context.request.extension, callback)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 347, in _fetch
    callback(False, buffer=buffer)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 112, in callback
    self.filters_runner.apply_filters(thumbor.filters.PHASE_AFTER_LOAD, transform)
  File "/usr/local/lib/python2.7/site-packages/thumbor/filters/__init__.py", line 81, in apply_filters
    callback()
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 110, in transform
    Transformer(self.context).transform(after_transform_cb)
  File "/usr/local/lib/python2.7/site-packages/thumbor/transformer.py", line 88, in transform
    self.smart_detect()
  File "/usr/local/lib/python2.7/site-packages/thumbor/transformer.py", line 123, in smart_detect
    self.do_image_operations()
  File "/usr/local/lib/python2.7/site-packages/thumbor/transformer.py", line 196, in do_image_operations
    self.resize()
  File "/usr/local/lib/python2.7/site-packages/thumbor/transformer.py", line 275, in resize
    self.engine.resize(self.target_width or 1, self.target_height or 1)  # avoiding 0px images
  File "/usr/local/lib/python2.7/site-packages/opencv_engine/engine.py", line 74, in resize
    cv.Resize(self.image, thumbnail, cv.CV_INTER_AREA)
error: src.type() == dst.type()
```

After some digging, it appears to be isolated to PNGs with **16 bits/channel** only. Opening xkobal's file in Photoshop reveals:

![screenshot 2015-02-22 15 10 20](https://cloud.githubusercontent.com/assets/423740/6320178/9eb4250a-baa5-11e4-838e-33fc338a0109.png)

Tried saving the same image at 8 bits/channel before running it through Thumbor, error goes away.

Hope this helps narrow down the issue.

**Comment by scorphus** [comment]
Hi, @sskylar! Yesterday I had time to tackle opencv-engine's issues and pull requests, but I worked until very late – as you can see from https://github.com/scorphus/opencv-engine/commit/83092d36bdb7cc3c29a4b30222877dd58e61344e – and only today I saw your commit. I'm adding some images to Thumbor's integration test which opencv-engine fails against, just like aforementioned fails. Glad you intend to contribute!

**Comment by sskylar** [comment]
@scorphus Great! I like your solution, wasn't sure the easiest way to get the bit depth but that definitely looks better.

Just tested your fix out and there is (at least) one case where it still doesn't work (same with mine).

First, the good news. These all work great now:

:+1: resize
:+1: crop
:+1: rotate
:+1: grayscale

Where it still has problems is on filters like `fill()` which I believe makes use of `gen_image` or `image_data_as_rgb` (`enable_alpha` also possibly affected, but I haven't confirmed).

Here is a sample 16-bit png with alpha:
![test alpha 16bit](https://cloud.githubusercontent.com/assets/423740/6336523/28aa081c-bb71-11e4-86a9-b6d562282197.png)

Download link in case GitHub messes with it: http://cdn2.dropmark.com/1/f5d0063c2484e5070f10feafbe55c6f6d26130dd/test.alpha.16bit.png

Using your fix, here's how `100x100/filters:grayscale():rotate(90)` looks:

![result2-test alpha 16bit](https://cloud.githubusercontent.com/assets/423740/6336468/d5398b44-bb70-11e4-9ead-a3398e09307c.png)

:+1: Perfect

With `filters:fill(blue)`:

![result-test alpha 16bit](https://cloud.githubusercontent.com/assets/423740/6336514/1ed627f8-bb71-11e4-90f7-1e38aa5ad693.png)

:-1: Hmm

For the record, I found I was able to solve by converting to 8bit in `create_image`. However, this was caused my image to lose alpha, so I'm not sure that's the best plan.

**Comment by xkobal** [comment]
Hello, thanks for the work. Any update on that point ?

Best regards.

Xavier

**Comment by scorphus** [comment]
Hello, @xkobal. We're still working on it. We've managed to make it stop crashing but some filters still can't deal too well with 16bit images, as of yet. We'll keep this issue updated.

**Comment by xkobal** [comment]
:thumbsup:

Thank you very much !
